Setup tmate session in case of failure

diff --git a/.github/workflows/on-push-build-and-deploy.yml b/.github/workflows/on-push-build-and-deploy.yml
--- a/.github/workflows/on-push-build-and-deploy.yml
+++ b/.github/workflows/on-push-build-and-deploy.yml
@@ -41,21 +41,25 @@ jobs:
       env:
         SFDC_TKN: ${{ secrets.sfdc_tkn }}
         SFDC_PASSWORD: ${{ secrets.sfdc_sandbox_integrationuser_pwd }}
-        TYPEFORM_CLIENTID: ${{ secrets.typeform_clientid }}
+        TYPEFORM_CLIENTID: ${{ secrets.typeform.clientid }}
         TYPEFORM_CLIENTSECRET: ${{ secrets.typeform_clientsecret }}
         TYPEFORM_TKN: ${{ secrets.typeform_tkn }}
       run: |
-        echo "Before replacing secrets:"
-        grep -E 'sfdc.tkn=|sfdc.password=|typeform.clientid=|typeform.clientsecret=|typeform.tkn=' src/main/resources/properties/sandbox.properties
+        set -e  # Exit immediately if a command exits with a non-zero status
+        echo "Checking if sandbox.properties file exists:"
+        if [ -f src/main/resources/properties/sandbox.properties ]; then
+          echo "sandbox.properties file exists. Here is its content before replacing secrets:"
+          cat src/main/resources/properties/sandbox.properties
+        else
+          echo "Error: sandbox.properties file does not exist."
+          exit 1
+        fi
     
         sed -i "s/sfdc.tkn=/sfdc.tkn=${{ secrets.sfdc_tkn }}/" src/main/resources/properties/sandbox.properties
         sed -i "s/sfdc.password=/sfdc.password=${{ secrets.sfdc_sandbox_integrationuser_pwd }}/" src/main/resources/properties/sandbox.properties
-        sed -i "s/typeform.clientid=/typeform.clientid=${{ secrets.typeform_clientid }}/" src/main/resources/properties/sandbox.properties
-        sed -i "s/typeform.clientsecret=/typeform.clientsecret=${{ secrets.typeform_clientsecret }}/" src/main/resources/properties/sandbox.properties
-        sed -i "s/typeform.tkn=/typeform.tkn=${{ secrets.typeform_tkn }}/" src/main/resources/properties/sandbox.properties
-    
-        echo "After replacing secrets:"
-        grep -E 'sfdc.tkn=|sfdc.password=|typeform.clientid=|typeform.clientsecret=|typeform.tkn=' src/main/resources/properties/sandbox.properties
+        sed -i "s/typeform.clientid=/typeform.clientid=${{ secrets.typeform.clientid }}/" src/main/resources/properties/sandbox.properties
+        sed -i "s/typeform.clientsecret=/typeform.clientsecret=${{ secrets.typeform.clientsecret }}/" src/main/resources/properties/sandbox.properties
+        sed -i "s/typeform.tkn=/typeform.tkn=${{ secrets.typeform.tkn }}/" src/main/resources/properties/sandbox.properties
     - name: Print effective-settings
       run: mvn help:effective-settings
     - name: Print effective-pom
@@ -73,6 +77,9 @@ jobs:
       with:
           name: artifacts
           path: target/*.jar
+    - name: Setup tmate session
+      if: failure()
+      uses: mxschmitt/action-tmate@v3
 
   deploy:
     needs: build
